config/routes.rb
Rails.application.routes.draw do   
 
  resource :feedback, only: %i[new create]
  root 'tests#index'

  devise_for :users, path: :gurus, path_names:{sign_in: :login, sign_out: :logout}, controllers: { confirmations: 'users/confirmations' }
  
  resources :tests, only: %i[index] do
    member do
      post :start
    end
  end

   resources :badges, only: %i[index] 
   get 'achievements', to: 'badges#achievements'
  
  resources :test_passages, only: %i[show update] do
    post :gist, to: 'gists#create'
    member do
      get :result
    end
  end


  namespace :admin do
    resources :gists
    resources :badges
    resources :tests do
      patch :update_inline, on: :member
      resources :questions, shallow: true do
        resources :answers, shallow: true
      end
    end
  end
end

app/models/badge.rb
class Badge < ApplicationRecord
  has_many :badge_users, dependent: :destroy
  has_many :users, through: :badge_users

  validates :title, :rule, :value, presence: true

end

app/controllers/admin/badges_controller.rb
class Admin::BadgesController < Admin::BaseController
  before_action :find_badge, only: %i[show edit update destroy]
  def index
    @badges = Badge.all
  end

  def new
    @badge = Badge.new
  end

  def create
    @badge = Badge.create(params_badge)
    redirect_to admin_badges_path
  end

  def show; end

  def edit; end

  def update
    if @badge.update(params_badge)
      redirect_to admin_badges_path
    else
      render :edit
    end
  end

  def destroy
    @badge.destroy
    redirect_to admin_badges_path
  end

  private

  def params_badge
    params.require(:badge).permit(:title, :picture, :rule, :value)
  end

  def find_badge
    @badge = Badge.find(params[:id])
  end
end

app/controllers/badges_controller.rb
class BadgesController < ApplicationController
  before_action :find_badge, only: %i[show]
  def index
    @badges = Badge.all
  end

  def achievements
    @user_badges = current_user.achievements
  end

  private

  def find_badge
    @badge = Badge.find(params[:id])
  end
end

app/views/admin/badges/_badge.html.erb
<tr class="text-center">
  <td><%= badge.title %></td>
  <td><%= octicon badge.picture, height:24 %></td>
  <td><%= link_to t('.show'), admin_badge_path(badge) %></td>
  <td><%= link_to t('.edit'), edit_admin_badge_path(badge) %></td>
  <td><%= link_to t('.delete'), admin_badge_path(badge), method: :delete %></td>
</tr>

app/views/admin/badges/_badge_form.html.erb
<%= render '/shared/errors', resource:[@badge]%>
<%= form_with model: [:admin, @badge], local: true do |form|%>
<p>
  <%= form.label :title, t('.title') %>
  <%= form.text_field :title%>
</p>
<p>
  <%= form.label :picture, 'Octicon'%>
  <%= form.text_field :picture%>
</p>
<p>
  <%= form.label :rule%>
  <%= form.text_field :rule%>
</p>

<p>
  <%= form.label :value%>
  <%= form.text_field :value%>
</p>


<p>
  <%= form.submit%>
</p>
<%end%>
<%= link_to t('.back'), admin_badges_path%>

app/views/admin/badges/edit.html.erb
<h1><%= t('.header')%></h1>
<%= render 'badge_form' %>

app/views/admin/badges/index.html.erb
<h1><%= t('.achievements')%></h1>

<%= link_to t('.new'), new_admin_badge_path %>

<div class="container col-12 col-md-8  ">
  <table class="table table-hover table-bordered">
    <thead>
      <tr class="table-success text-center">
        <th>
          <%= t('.achievements')%>
        </th>
        <th>
          Octicon
        </th>
        <th colspan="3">
          <%= t('.actions') %>
        </th>
      </tr>
    </thead>
    <tbody>
      <%= render @badges %>
    </tbody>
  </table>
</div>

app/views/admin/badges/new.html.erb
<h1><%= t('.create')%></h1>
<%= render 'badge_form' %>

app/views/admin/badges/show.html.erb
<p><%= t('.title')%>: <%= @badge.title%></p>
<p><%= t('.rule')%>: <%= @badge.rule%></p>
<p><%= t('.value')%>: <%= @badge.value%></p>
<%= link_to t('.edit'), edit_admin_badge_path(@badge) %><br>
<%= link_to t('.back'), admin_badges_path %>