config/routes.rb
Rails.application.routes.draw do   
 
  resource :feedback, only: %i[new create]
  root 'tests#index'

  devise_for :users, path: :gurus, path_names:{sign_in: :login, sign_out: :logout}, controllers: { confirmations: 'users/confirmations' }
  
  resources :tests, only: %i[index] do
    member do
      post :start
    end
  end

   resources :badges, only: %i[index] 
   get 'achievements', to: 'badges#achievements'
  
  resources :test_passages, only: %i[show update] do
    post :gist, to: 'gists#create'
    member do
      get :result
    end
  end


  namespace :admin do
    resources :gists
    resources :badges
    resources :tests do
      patch :update_inline, on: :member
      resources :questions, shallow: true do
        resources :answers, shallow: true
      end
    end
  end
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :test
  has_many :answers, dependent: :destroy
  has_many :test_passages, dependent: :destroy
  has_many :gists, dependent: :destroy

  validates :body, presence: true

  delegate :correct_answers, to: :answers
end

app/models/test_passage.rb
class TestPassage < ApplicationRecord
  TEST_RESULT_SUCCESS = 85

  belongs_to :test
  belongs_to :user
  belongs_to :current_question, class_name: 'Question', foreign_key: 'question_id', optional: true
  before_validation :before_validation_set_first_question, on: :create
  before_validation :before_validation_set_next_question, on: :update
  def accept!(answer_ids)
    self.correct_questions += 1 if correct_answers?(answer_ids)
    self.success = true if test_success?
    save!
  end

  def completed?
    current_question.nil?
  end

  def test_result
    (correct_questions / test.questions_count.to_f * 100).floor(2)
  end

  def test_success?
    test_result >= TEST_RESULT_SUCCESS
  end
  
  def current_question_number
    if next_question || current_question
      test.questions.order(:id).where('id < ?', current_question).count + 1
    else
      test.questions.count
    end
  end

  def set_time_left
    test.time_for_passage_in_sec - (Time.now - created_at)
  end

  def timer_exist?
    test.time_for_passage ? true : false
  end

  private

  def correct_answers?(answer_ids)
    correct_answers_count = correct_answers.count
    (correct_answers_count == correct_answers.where(id: answer_ids).count) &&
      correct_answers_count == answer_ids.count
  end

  def correct_answers
    current_question.correct_answers
  end

  def next_question
    test.questions.order(:id).where('id > ?', current_question&.id).first
  end

  def before_validation_set_first_question
    self.current_question = test.questions.first if test.present?
  end

  def before_validation_set_next_question
    self.current_question = next_question
  end
end

app/controllers/test_passages_controller.rb
class TestPassagesController < ApplicationController
  before_action :set_test_passage, only: %i[show update result]
  def show
  end

  def update
    @test_passage.accept!(params[:answer_ids])
    if @test_passage.completed? || @test_passage.set_time_left.negative?
      @test_passage.current_question = nil
      TestsMailer.completed_test(@test_passage).deliver_now
      @test_passage.test_result
      redirect_to result_test_passage_path(@test_passage)
    else
      render :show
    end
  end

  def result
    BadgeService.define_badges(@test_passage)
  end

  private

  def set_test_passage
    @test_passage = TestPassage.find(params[:id])
  end

end

app/helpers/test_passages_helper.rb
module TestPassagesHelper
end

app/views/test_passages/_progress_bar.html.erb
  <div class= 'col-12 col-md-6'>
  <span><%= test_passage.current_question_number %> <%= t('.from')%> <%= t('.questions_counter', count: test_passage.test.questions_count)%></span>
  <%= content_tag :div, class: 'progress-bar', data:{question_number: test_passage.current_question_number, total_questions: test_passage.test.questions_count, completed: test_passage.completed?} do  %>
  <%end%>
  </div>

app/views/test_passages/_timer.html.erb
<%= content_tag :div, class: 'timer col-12 col-md-6', data:{time_left: test_passage.set_time_left} do %>
  <h3 class='time'></h3>
<%end%>

app/views/test_passages/result.html.erb
<h1><%= t( '.completed', test: @test_passage.test.title)%> </h1>
 <%= render 'test_passages/progress_bar', test_passage: @test_passage%>

  <div class="form-group col-12 col-md-3 ml-3 mt-5">
    <div clas="card">
      <%if  @test_passage.test_success?%>
      <div class="card-body border border-success">
          <h5 class='card-title'> <%= t('.success', user: current_user.username, result: @test_passage.test_result)%></h5>
      </div>
      <%else%>
        <div class="card-body border border-danger">
        	<h5 class='card-title'><%= t('.fail', user: current_user.username, result: @test_passage.test_result)%></h5>
        </div>
      <%end%>
        <p><%= button_to t('.back'), tests_path, class: "btn btn-primary", method: :get %></p>
      </div>
    </div>
  </div>

app/views/test_passages/show.html.erb
<h1> <%= t('.passind_test',  test: @test_passage.test.title) %></h1>

<p>
	
		<%= render 'test_passages/progress_bar', test_passage: @test_passage%>
		<% if @test_passage.timer_exist? %>
			<%= render 'test_passages/timer', test_passage: @test_passage, time_left: @test_passage.set_time_left%>
		<% end %>
		<div class="form-group col-12 col-md-6 ml-3">
			
		<br>
			<div class="card">
			  <div class="card-body">
					<%= @test_passage.current_question.body%>
				</div>
			</div>
		</div>
	<div class="form-group col-12 col-md-6 ml-3">
		<%= form_with url: test_passage_path(@test_passage), local: true, method: :put do |form|%>
		  <div class="card">
			  <ol class="list-group list-group-flush">
			  <%= form.collection_check_boxes :answer_ids, @test_passage.current_question.answers, :id, :body, include_hidden: false do |b| %>
			    <li class="list-group-item">
			    	<%= b.check_box id:"answer_ids_#{b.object.id}" %>
			    	<%= b.label%>
			    </li>
			  <%end%>
			  </ol>
			</div>
	</div>
	  <div class="form-group col-12 col-md-6 ml-3">
	  	<%= form.submit t('.next'), class: "btn btn-success js_auto_submit" %>
	  	<%= link_to t('.create_gist'), test_passage_gist_path(@test_passage), method: :post%>
	  </div>
			<%end%>
		</div>

</p>