config/routes.rb
Rails.application.routes.draw do   
 
  resource :feedback, only: %i[new create]
  root 'tests#index'

  devise_for :users, path: :gurus, path_names:{sign_in: :login, sign_out: :logout}, controllers: { confirmations: 'users/confirmations' }
  
  resources :tests, only: %i[index] do
    member do
      post :start
    end
  end

   resources :badges, only: %i[index] 
   get 'achievements', to: 'badges#achievements'
  
  resources :test_passages, only: %i[show update] do
    post :gist, to: 'gists#create'
    member do
      get :result
    end
  end


  namespace :admin do
    resources :gists
    resources :badges
    resources :tests do
      patch :update_inline, on: :member
      resources :questions, shallow: true do
        resources :answers, shallow: true
      end
    end
  end
end

app/models/admin.rb
class Admin < User
  validates :first_name, :last_name, presence: true
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question

  scope :correct_answers, -> { where(correct: true) }

  validates :body, presence: true
  validate :validate_question_number_answers, on: :create

  private

  def validate_question_number_answers
    if self.class.where(question_id: question_id).count >= 4
      errors.add(:question_id, message: 'Question can contain 4 answers maximum')
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/badge.rb
class Badge < ApplicationRecord
  has_many :badge_users, dependent: :destroy
  has_many :users, through: :badge_users

  validates :title, :rule, :value, presence: true

end

app/models/badge_user.rb
class BadgeUser < ApplicationRecord
  belongs_to :badge
  belongs_to :user
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :tests

  default_scope { order(title: :asc) }

  validates :title, presence: true
end

app/models/gist.rb
class Gist < ApplicationRecord
  belongs_to :question
  belongs_to :user

  scope :gists_with_author_and_question, -> { select(:email, :question_id, :body, :gist_url).joins(:user, :question) }
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :test
  has_many :answers, dependent: :destroy
  has_many :test_passages, dependent: :destroy
  has_many :gists, dependent: :destroy

  validates :body, presence: true

  delegate :correct_answers, to: :answers
end

app/models/test.rb
class Test < ApplicationRecord
  belongs_to :category
  has_many :questions, dependent: :destroy
  has_many :test_passages
  has_many :passed_users, through: :test_passages, source: :user
  belongs_to :author, class_name: 'User', foreign_key: 'user_id'

  scope :tests_for_passing, -> { where(under_construction: false) }
  scope :easy, -> { where(level: 0..1) }
  scope :middle, -> { where(level: 2..4) }
  scope :hard, -> { where(level: 5..Float::INFINITY) }
  scope :tests_with_category, -> { joins(:category) }

  before_validation :test_correctness
  validates :title, presence: true, uniqueness: { scope: :level, message: 'Title and level combination must be unique' }
  validates :level, numericality: { only_integer: true }

  def self.tests_by_category(title)
    tests_with_category.where('categories.title=?', title).order(title: :desc).pluck(:title)
  end

  def time_for_passage_in_sec
    time_for_passage*60 if time_for_passage
  end

  def correct_test?
    !(questions.empty? || questions.left_outer_joins(:answers).exists?(answers: { id: nil }))
  end

  def test_correctness
    self.under_construction = true unless correct_test?
  end

  delegate :count, to: :questions, prefix: true
end

app/models/test_passage.rb
class TestPassage < ApplicationRecord
  TEST_RESULT_SUCCESS = 85

  belongs_to :test
  belongs_to :user
  belongs_to :current_question, class_name: 'Question', foreign_key: 'question_id', optional: true
  before_validation :before_validation_set_first_question, on: :create
  before_validation :before_validation_set_next_question, on: :update
  def accept!(answer_ids)
    self.correct_questions += 1 if correct_answers?(answer_ids)
    self.success = true if test_success?
    save!
  end

  def completed?
    current_question.nil?
  end

  def test_result
    (correct_questions / test.questions_count.to_f * 100).floor(2)
  end

  def test_success?
    test_result >= TEST_RESULT_SUCCESS
  end
  
  def current_question_number
    if next_question || current_question
      test.questions.order(:id).where('id < ?', current_question).count + 1
    else
      test.questions.count
    end
  end

  def set_time_left
    test.time_for_passage_in_sec - (Time.now - created_at)
  end

  def timer_exist?
    test.time_for_passage ? true : false
  end

  private

  def correct_answers?(answer_ids)
    correct_answers_count = correct_answers.count
    (correct_answers_count == correct_answers.where(id: answer_ids).count) &&
      correct_answers_count == answer_ids.count
  end

  def correct_answers
    current_question.correct_answers
  end

  def next_question
    test.questions.order(:id).where('id > ?', current_question&.id).first
  end

  def before_validation_set_first_question
    self.current_question = test.questions.first if test.present?
  end

  def before_validation_set_next_question
    self.current_question = next_question
  end
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :trackable, :confirmable
  has_many :test_passages, dependent: :destroy
  has_many :passed_tests, through: :test_passages, source: :test
  has_many :created_tests, class_name: 'Test'
  has_many :badge_users, dependent: :destroy
  has_many :badges, through: :badge_users

  def completed_tests(level)
    passed_tests.where(level: level)
  end

  def achievements
    @badges = badges.distinct.order(updated_at: :desc)
  end

  def succesfully_passed_tests
    passed_tests.select { |test_passage| test_passage.test_success? }
  end

  def test_passage(test)
    test_passages.order(id: :desc).find_by(test_id: test.id)
  end

  def admin?
    is_a?(Admin)
  end

  def full_name
    if first_name && last_name
      "#{first_name} #{last_name}"
    else
      'Stranger'
    end
  end
end

app/controllers/gists_controller.rb
class GistsController < ApplicationController
  before_action :set_test_passage

  def create
    gist = GistQuestionService.new(@test_passage.current_question)
    gist.call
    if gist.success?
      gist_url = gist.url_hash
      @gist = Gist.create(user_id: @test_passage.user_id, question_id: @test_passage.current_question.id,
                          gist_url: gist_url)
      flash.now[:notice] = t('.gist_success_html', gist: helpers.link_to_gist(@gist)).html_safe
    else
      flash.now[:notice] = t('.gist_fail')
    end
    render '/test_passages/show'
  end

  private

  def set_test_passage
    @test_passage = TestPassage.find(params[:test_passage_id])
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  COLORS = { alert: 'danger', notice: 'warning', greeting: 'success', goodbye: 'primary' }

  def current_year
    "Year:#{Time.zone.today}"
  end

  def github_url(author, repo)
    link_to(author.to_s, "https:/github.com/#{author}/#{repo}", target: '_blank', rel: 'noopener')
  end

  def flash_message(flag)
    tag.span(flash[flag]) if flash[flag]
  end

  def bootstrap_color(flag)
    "alert-#{COLORS[flag.to_sym]}"
  end
end

app/helpers/feedbacks_helper.rb
module FeedbacksHelper
end

app/helpers/gists_helper.rb
module GistsHelper
  GIST_API_ENDPOINT = 'https://gist.github.com/'

  def link_to_gist(gist)
    gist_url = GIST_API_ENDPOINT + gist.gist_url + '.git'
    link_to(gist.gist_url, gist_url, target: '_blank', rel: 'noopener')
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
  def question_header(question)
    title = question.test.title
    if question.new_record?
      "Create new #{title} Question"
    else
      "Edit #{title} Question"
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tests_helper.rb
module TestsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TestGuru</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render '/shared/header'%>
    <%= render '/shared/flash'%>
    <%= yield %>
    <%= render '/shared/footer'%>
  </body>
</html>

app/views/shared/_errors.html.erb
<% resource.each do |resource|%>

<% if resource.present? && resource.errors.present?%>
	
  <%= content_tag :div, class: 'resource-errors', data: {resource_id: resource.id} do %>
		<h2> <%= t('.errors_counter', count: resource.errors.count) %>:</h2>
		<ul>
			<%resource.errors.full_messages.each do  |message|%>
			<li><%= message%></li>
			<%end%>
		</ul>
	<% end %>
<%end%>

<%end%>

app/views/shared/_flash.html.erb
<% flash.each do |flag, _message|%>
<div class="col-12 col-md-4 mt-3">
  <%= tag.div class: ["alert", bootstrap_color(flag), "alert-dismissible", "fade", "show"], role: "alert" do  %>
    <%= flash_message(flag)%>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
  <%end%>
  </div>
<%end%>

app/views/shared/_footer.html.erb
<footer >
<h6>About author:skrepkoed </h6>
<p>
	TestGuru это приложение позволяющее создавать, проходить и управлять тестами на различную тематику, а также публиковать результаты тестов в соцсетях. В приложении предусмотрены роли Пользователя и Администратора и разграничение прав доступа на основе этих ролей. Тесты могут создаваться только Администраторами. TestGuru разрабатывается в рамках курса онлайн-школы <a href="https:/thinknetica.com" target="_blank">Thinknetica</a> 
</p>
<p>Github: <%=github_url('skrepkoed', 'TestGuru')%></p>
<p><%=current_year%></p>
</footer>

app/views/shared/_header.html.erb
<header>
  <nav class='navbar navbar-expand-lg navbar-light bg-light'>
    <% unless current_user&.admin?%>
    <div class='navbar-brand'><%= link_to 'TestGuru', '/'%> </div>
    <%else%>
    <div class='navbar-brand'><%= link_to 'TestGuru', '/'%> </div>
    <div class='navbar-brand'><%= link_to 'TestGuruAdmin', admin_tests_path%> </div>
    <div class='navbar-brand'><%= link_to t('.achievements'), admin_badges_path%> </div>
    <div class='navbar-brand'><%= link_to t('.gists'), admin_gists_path%> </div>
    <%end%>
    <div class='navbar-nav flex-fill justify-content-end'>
      <% if user_signed_in?%>
        <%= link_to 'Log out', destroy_user_session_path, method: :delete, class: "nav-link" %>
        <%= link_to t('.achievements'), achievements_path, class: "nav-link"%>
        <span class="navbar-text">Welcome Guru <%= current_user.username%></span>
        <span><%= link_to 'Feedback', new_feedback_path, class: "nav-link" %> </span>
      <%else%>
        <%= link_to 'Log in', new_user_session_path, class: "nav-link"%>
        <%= link_to 'Sign up', new_user_registration_path, class: "nav-link"%>
         
      <%end%>
  
      </div>
  </nav>
</header>

app/views/shared/_questions_list.html.erb
<p><%= link_to t('.create'), new_admin_test_question_path(test)%></p>
<%= link_to t('.back'), admin_tests_path%>
<ol>
<% test.questions.each do |question|%>
	<li>
		<p><%= question.body%></p>
		<p>
			<%=link_to t('.show'), admin_question_path(question)%>|
			<%=link_to t('.edit'), edit_admin_question_path(question)%>|
			<%=link_to t('.delete'), admin_question_path(question), method: :delete%>
		</p>
	</li>
<%end%>
</ol>