config/routes.rb
Rails.application.routes.draw do   
 
  resource :feedback, only: %i[new create]
  root 'tests#index'

  devise_for :users, path: :gurus, path_names:{sign_in: :login, sign_out: :logout}, controllers: { confirmations: 'users/confirmations' }
  
  resources :tests, only: %i[index] do
    member do
      post :start
    end
  end

   resources :badges, only: %i[index] 
   get 'achievements', to: 'badges#achievements'
  
  resources :test_passages, only: %i[show update] do
    post :gist, to: 'gists#create'
    member do
      get :result
    end
  end


  namespace :admin do
    resources :gists
    resources :badges
    resources :tests do
      patch :update_inline, on: :member
      resources :questions, shallow: true do
        resources :answers, shallow: true
      end
    end
  end
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question

  scope :correct_answers, -> { where(correct: true) }

  validates :body, presence: true
  validate :validate_question_number_answers, on: :create

  private

  def validate_question_number_answers
    if self.class.where(question_id: question_id).count >= 4
      errors.add(:question_id, message: 'Question can contain 4 answers maximum')
    end
  end
end

app/controllers/admin/answers_controller.rb
class Admin::AnswersController < Admin::BaseController
  before_action :set_answer, only: %i[show edit update destroy]
  before_action :find_question, only: %i[new create]

  def show; end

  def new
    @answer = @question.answers.new
  end

  def edit
    @question = @answer.question
  end

  def create
    @answer = @question.answers.new(answer_params)
    if @answer.save
      redirect_to [:admin, @answer]
    else
      render :new
    end
  end

  def update
    if @answer.update(answer_params)
      redirect_to [:admin, @answer]
    else
      render :edit
    end
  end

  def destroy
    @answer.destroy
    redirect_to [:admin, @answer.question]
  end

  private

  def set_answer
    @answer = Answer.find(params[:id])
  end

  def find_question
    @question = Question.find(params[:question_id])
  end

  def answer_params
    params.require(:answer).permit(:body, :correct)
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/views/admin/answers/_answer.html.erb
<li>
	<%= answer.body%><br>
	<%= answer.correct%><br>
	<%= link_to 'Show', admin_answer_path(answer)%>|
	<%= link_to 'Delete', admin_answer_path(answer), method: :delete %>|
	<%= link_to 'Edit', edit_admin_answer_path(answer)%>|
</li>

app/views/admin/answers/_form.html.erb
<%= render '/shared/errors', resource: answer%>
<%= form_with(model: [:admin, *answer], local: true) do |form| %>
    <p>
		<%= form.label :body%>
		<%= form.text_area :body, rows:7, cols:60%>
	</p>

	<p>
		<%= form.label :correct%>
		<%= form.check_box :correct, id: :answer_correct%>
	</p>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>
<%= link_to 'Back', admin_question_path(answer.last.question)%>

app/views/admin/answers/edit.html.erb
<h1>Editing Answer</h1>

<p>
	<%= @answer.question.body%>
</p>

<%= render 'form', answer: [@answer] %>

app/views/admin/answers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Answers</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @answers.each do |answer| %>
      <tr>
        <td><%= link_to 'Show', admin_answer %></td>
        <td><%= link_to 'Edit', edit_admin_answer_path(answer) %></td>
        <td><%= link_to 'Destroy', admin_answer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Answer', new_answer_path %>

app/views/admin/answers/new.html.erb
<h1>New Answer</h1>

<p>
	<%= @question.body%>
</p>

<%= render 'form', answer: [@question, @answer] %>

app/views/admin/answers/show.html.erb
<p id="notice"><%= notice %></p>
<p>
	<%= @answer.question.body%>
</p>

<p>Answer: <%= @answer.body%></p>
<p>Correct: <%= @answer.correct%></p>
<%= link_to 'Edit', edit_admin_answer_path(@answer) %> |
<%= link_to 'Back', admin_question_path(@answer.question)%>